version: '3'

services:
    mysql:
        build:
            context: ./
            dockerfile: mysql.Dockerfile
        container_name: kasperhansen-mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: app
        ports:
            - "3306:3306"
        restart: unless-stopped
        volumes:
            - ./mysql/:/var/lib/mysql/

    webpack:
        build:
            context: ./
            dockerfile: node.Dockerfile
        command: npx webpack build --mode development --watch --progress
        container_name: kasperhansen-webpack
        restart: unless-stopped
        volumes:
            - ./less:/var/www/less
            - ./public/assets:/var/www/public/assets
            - ./templates/assets:/var/www/templates/assets
        working_dir: /var/www